dataset: "~/mnist/mnist.npz"
param_cache: "params.hdf5"
model_name: "test000"
output_dir: "~/mnist"
neighbor_graph: "~/mnist/full_train_neighbors.json"

hyperparams:
  learning_rate: 0.02
  margin_same: 0.0
  margin_diff: 1.0
  batch_size: 50

train_params:
  max_iter: 150
  save_freq: 50
  print_freq: 25

verbose: yes
